version: "3.9"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/prisma/local
    environment:
      - PORT=3000
    command: sh -c "sleep 20s ;yarn prisma:up ;yarn start"
    depends_on:
      - db
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pelandodb
    ports:
      - "5432:5432"
    volumes:
      - ./infra:/var/lib/postgresql/data
    